site_name: WALIS
nav:
    - Home: index.md
    - Relative Sea Level: Relative Sea Level.md
    - Type of RSL indicator: Type of RSL indicator.md
    - Geographic positioning: Geographic positioning.md
    - Elevation measurement: Elevation measurement.md
    - Sea Level Datum: Sea Level Datum.md
    - Common fields for dating techniques: dating.md
    - U-Series: U-Series.md
    - AAR: AAR.md
    - Luminescence: LUM.md
    - Electron Spin Resonance: ESR.md
    - Chronostratigraphy: Chronostratigraphy.md
    - Other age constraints: Other_age.md
    - About: about.md
    - How to cite: citation.md
markdown_extensions:
  - footnotes
theme: readthedocs 