site_name: WALIS
nav:
    - Home: index.md
    - Relative Sea Level: Relative Sea Level.md
    - Type of RSL indicator: Type of RSL indicator.md
    - Geographic positioning: Geographic positioning.md
    - About: about.md
markdown_extensions:
  - footnotes
theme: readthedocs 